/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package monitoring

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.parameters.arguments.argument
import com.github.ajalt.clikt.parameters.options.default
import com.github.ajalt.clikt.parameters.options.option
import com.github.ajalt.clikt.parameters.types.file
import com.github.ajalt.clikt.parameters.types.int
import java.io.BufferedReader
import java.io.FileReader

fun main(args: Array<String>) = MonitorApp().main(args)

class MonitorApp : CliktCommand() {

    private val count by argument().file()
    private val threshold: Int by option(help = "Number of greetings").int().default(1)

    override fun run() {
        val bufferedReader = BufferedReader(FileReader(count))
        val dataRepository = DataRepository()

        HttpLogMonitor(dataRepository, bufferedReader).handleLogs(threshold)
    }
}
