/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package monitoring

import org.apache.commons.math3.stat.descriptive.DescriptiveStatistics
import java.io.BufferedReader
import java.io.FileReader
import java.time.Instant

fun main(args: Array<String>) {
    val bufferedReader = BufferedReader(FileReader("/Users/mr/projects/monitoring/sample_csv.txt"))
    readFile(bufferedReader)
    println()
}

fun readFile(bufferedReader: BufferedReader) {
    val header = bufferedReader.readLine()
    var line = bufferedReader.readLine()
    var initTimestamp: Instant? = null
    val statistics = DescriptiveStatistics()

    while (line != null) {
        val httpLog = HttpLogParser.parse(line)
        initTimestamp = initTimestamp ?: httpLog.date
        val httpLogs = mutableSetOf<HttpLog>()
        if (httpLog.date.epochSecond - initTimestamp.epochSecond >= 10) {
            println(generateStatistics(httpLogs, initTimestamp))
            initTimestamp = httpLog.date
        }
        httpLogs.clear()
        httpLogs.add(httpLog)
        line = bufferedReader.readLine()
    }
}

fun generateStatistics(httpLogs: MutableSet<HttpLog>, initTimestamp: Instant): String {
    val sectionMapping: Map<String, List<HttpLog>> = httpLogs.groupBy { it.section }
    return "$initTimestamp :" + sectionMapping
}
